-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE potterbase.piece_stage_history
-- ADD CONSTRAINT stage_valid CHECK (
--   stage = ANY (ARRAY[
--     'lump'::text,
--     'formed'::text,
--     'trimmed'::text,
--     'bisque'::text,
--     'glazed'::text,
--     'fired'::text,
--     'archived'::text,
--     'failed'::text
--   ])
-- );
